name: Default Branch

on:
  push:
    branches:
    - main

jobs:
  test-master:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

  build-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: test-master
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Build packages
      run: mage go:crossBuild
