name: Pull Request

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

    - name: Build packages
      run: mage go:crossBuild

  automerge:
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.DOPS_SRE_PAT }}
