name: Release

on:
  release:
    types:
    - published

jobs:
  test-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

  build-and-publish-packages:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: test-release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: elisa-actions/setup-go-and-mage@v1

    - name: Run lint
      run: mage go:lint

    - name: Run test
      run: mage go:unitTest

    - name: Build packages
      run: mage go:crossBuild

    - name: Make files
      run: |
        mkdir -p files
        cp target/bin/linux/amd64/resource-advisor files/resource-advisor-linux-amd64
        cp target/bin/linux/amd64/resource-advisor.sha256 files/resource-advisor-linux-amd64.sha256
        cp target/bin/linux/arm64/resource-advisor files/resource-advisor-linux-arm64
        cp target/bin/linux/arm64/resource-advisor.sha256 files/resource-advisor-linux-arm64.sha256
        cp target/bin/darwin/amd64/resource-advisor files/resource-advisor-darwin-amd64
        cp target/bin/darwin/amd64/resource-advisor.sha256 files/resource-advisor-darwin-amd64.sha256
        cp target/bin/darwin/arm64/resource-advisor files/resource-advisor-darwin-arm64
        cp target/bin/darwin/arm64/resource-advisor.sha256 files/resource-advisor-darwin-arm64.sha256
        cp target/bin/windows/amd64/resource-advisor files/resource-advisor-windows-amd64
        cp target/bin/windows/amd64/resource-advisor.sha256 files/resource-advisor-windows-amd64.sha256

    - name: Upload all binaries and checksums
      uses: softprops/action-gh-release@v1
      with:
        files: |
          files/**
